### ISSUE TITLE
.gts test files not working in 2.2.2

### ISSUE THREAD

**Issue by BoussonKarel** [emberjs/babel-plugin-ember-template-compilation#41]
Since the upgrade to `babel-plugin-ember-template-compilation` version `2.2.2`, my test files with template imports (`gts` files) are not loading anymore.

In QUnit I'm getting 1 global failure:
```
1. Error: 
Error: Could not find module `ember-template-compiler` imported from `@ember/template-compilation/index`
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
Source: 	
Error: 
Error: Could not find module `ember-template-compiler` imported from `@ember/template-compilation/index`
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
TypeError: Cannot read properties of undefined (reading 'exports')
    at eval (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:11:62)
    at eval (webpack://__ember_auto_import__/./node_modules/qunit/qunit/qunit.js?:376:140)
```

and all my gts test files have an error too:
```
1. Died on test #1: Cannot read properties of undefined (reading 'exports')
    at TestLoader.moduleLoadFailure (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:12:301)
    at TestLoader.require (http://localhost:4304/assets/test-support.js:7438:14)
    at TestLoader.loadModules (http://localhost:4304/assets/test-support.js:7430:14)
    at loadTests (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:25:42)
    at start (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/index.js?:83:119)
    at Module.callback (http://localhost:4304/assets/tests.js:4831:25)
    at Module.exports (http://localhost:4304/assets/vendor.js:125:32)@ 0 ms
Source: 	
TypeError: Cannot read properties of undefined (reading 'exports')
    at Module._reify (http://localhost:4304/assets/vendor.js:162:59)
    at Module.reify (http://localhost:4304/assets/vendor.js:149:27)
    at Module.exports (http://localhost:4304/assets/vendor.js:123:10)
    at Module._reify (http://localhost:4304/assets/vendor.js:162:59)
    at Module.reify (http://localhost:4304/assets/vendor.js:149:27)
    at Module.exports (http://localhost:4304/assets/vendor.js:123:10)
    at requireModule (http://localhost:4304/assets/vendor.js:46:18)
    at TestLoader.require (http://localhost:4304/assets/test-support.js:7436:9)
    at TestLoader.loadModules (http://localhost:4304/assets/test-support.js:7430:14)
    at loadTests (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:25:42)
```
or
```
1. Died on test #1: Could not find module `ember-template-compiler` imported from `@ember/template-compilation/index`
    at TestLoader.moduleLoadFailure (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:12:301)
    at TestLoader.require (http://localhost:4304/assets/test-support.js:7438:14)
    at TestLoader.loadModules (http://localhost:4304/assets/test-support.js:7430:14)
    at loadTests (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:25:42)
    at start (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/index.js?:83:119)
    at Module.callback (http://localhost:4304/assets/tests.js:4831:25)
    at Module.exports (http://localhost:4304/assets/vendor.js:125:32)@ 0 ms
Source: 	
Error: Could not find module `ember-template-compiler` imported from `@ember/template-compilation/index`
    at missingModule (http://localhost:4304/assets/vendor.js:266:11)
    at findModule (http://localhost:4304/assets/vendor.js:277:7)
    at Module.findDeps (http://localhost:4304/assets/vendor.js:187:24)
    at findModule (http://localhost:4304/assets/vendor.js:281:11)
    at Module.findDeps (http://localhost:4304/assets/vendor.js:187:24)
    at findModule (http://localhost:4304/assets/vendor.js:281:11)
    at requireModule (http://localhost:4304/assets/vendor.js:43:15)
    at TestLoader.require (http://localhost:4304/assets/test-support.js:7436:9)
    at TestLoader.loadModules (http://localhost:4304/assets/test-support.js:7430:14)
    at loadTests (webpack://__ember_auto_import__/./node_modules/ember-qunit/dist/test-loader.js?:25:42)
```

**Comment by BoussonKarel** [comment]
Closing because I see this is a duplicate of #36
